name = "fading"
description = "`fading` support."
id = "fading"
version = "0.0.0"
schema_version = 1
authors = ["tkoyasak"]
repository = "https://github.com/tkoyasak/fading-crates"

[language_servers.fading]
name = "fading ls"
language = "Markdown"
