# https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference
version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      cargo-dependencies:
        applies-to: version-updates
        update-types:
          - minor
          - patch

  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "react-server-dom-webpack"
    groups:
      oxc:
        applies-to: version-updates
        patterns:
          - "oxfmt"
          - "oxlint"
          - "oxlint-tsgolint"
      bun-dependencies:
        applies-to: version-updates
        update-types:
          - minor
          - patch
