version: 2

registries:
  flatt-npm:
    type: npm-registry
    url: https://npm.flatt.tech

updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
    allow:
      - dependency-type: all
    groups:
      cargo-dependencies:
        applies-to: version-updates
        update-types:
          - minor
          - patch

  - package-ecosystem: bun
    directory: /
    registries:
      - flatt-npm
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
    allow:
      - dependency-type: all
    groups:
      bun-dependencies:
        applies-to: version-updates
        update-types:
          - minor
          - patch
