version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
    allow:
      - dependency-type: all
    groups:
      cargo-dependencies:
        applies-to: version-updates
        update-types:
          - minor
          - patch

  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
    allow:
      - dependency-type: all
    groups:
      react:
        applies-to: version-updates
        patterns:
          - "react"
          - "react-dom"
          - "react-server-dom-webpack"
      bun-dependencies:
        applies-to: version-updates
        update-types:
          - minor
          - patch
