[workspace]
members = ["crates/ls", "crates/workflow", "crates/zed"]
resolver = "3"

[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.89.0" # https://github.com/actions/runner-images

[workspace.dependencies]
anyhow = { version = "1.0.100" }
chrono = { version = "0.4.42" }
crop = { version = "0.4.3", features = ["utf16-metric"] }
dashmap = { version = "6.1.0" }
octocrab = { version = "0.46.0" }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.47.1", features = ["rt-multi-thread", "macros", "io-std"] }
toml = { version = "0.9.7" }
tower-lsp-server = { version = "0.22.1" }
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.20" }
zed_extension_api = { version = "0.7.0" }
