# https://secretspec.dev/reference/configuration/
[project]
name = "fading"
revision = "1.0"

[profiles.development]
FADING_CLI_CF_ACCOUNT_ID = { description = "cloudflare account id", required = false }
FADING_CLI_CF_API_TOKEN = { description = "cloudflare api token", required = false }
FADING_CLI_KV_NAMESPACE_ID = { description = "cloudflare kv namespace id", required = false }
FADING_CLI_R2_BUCKET = { description = "cloudflare r2 bucket name", required = false }
FADING_CLI_R2_ACCESS_KEY_ID = { description = "r2 api token access key", required = false }
FADING_CLI_R2_SECRET_ACCESS_KEY = { description = "r2 api token secret key", required = false }
FADING_CLI_ENCRYPTION_KEY = { description = "aes-256-gcm key for r2 bundle", required = false }
