# Configuration file for `SecretSpec`, a declarative secrets manager for development workflows written in Rust.
# See https://secretspec.dev/reference/configuration/ for more information.

[project]
name = "fading"
revision = "1.0"

[profiles.development]
FADING_CLI_CF_ACCOUNT_ID = { description = "cloudflare account id", required = false }
FADING_CLI_R2_BUCKET = { description = "cloudflare r2 bucket name", required = false }
FADING_CLI_R2_ACCESS_KEY_ID = { description = "r2 api token access key", required = false }
FADING_CLI_R2_SECRET_ACCESS_KEY = { description = "r2 api token secret key", required = false }
FADING_CLI_ENCRYPTION_KEY = { description = "aes-256-gcm key for r2 bundle", required = false }
