[package]
name = "fading-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "fading"
path = "src/main.rs"

[dependencies]
fading-ls.workspace = true

anyhow.workspace = true
hex.workspace = true
hmac.workspace = true
jiff.workspace = true
mac-notification-sys.workspace = true
sha2.workspace = true
serde_json.workspace = true
tokio.workspace = true
pulldown-cmark.workspace = true
ureq.workspace = true
xflags.workspace = true
xshell.workspace = true

[dev-dependencies]
proptest.workspace = true
