[package]
name = "fading-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "fading"
path = "src/main.rs"

[dependencies]
fading-ls.workspace = true

anyhow.workspace = true
aes-gcm.workspace = true
base16ct.workspace = true
jiff.workspace = true
mac-notification-sys.workspace = true
shiguredo_s3.workspace = true
tokio.workspace = true
pulldown-cmark.workspace = true
ureq.workspace = true
xflags.workspace = true
xshell.workspace = true
