xflags::xflags! {
    src "./src/flags.rs"

    /// CLI for the `fading` language
    cmd fading {

        /// Start the language server
        cmd ls {}

        /// Notify of the time
        cmd notify {}
    }
}

// generated start
// The following code is generated by `xflags` macro.
// Run `env UPDATE_XFLAGS=1 cargo build` to regenerate.
#[derive(Debug)]
pub struct Fading {
    pub subcommand: FadingCmd,
}

#[derive(Debug)]
pub enum FadingCmd {
    Ls(Ls),
    Notify(Notify),
}

#[derive(Debug)]
pub struct Ls;

#[derive(Debug)]
pub struct Notify;

impl Fading {
    #[allow(dead_code)]
    pub fn from_env_or_exit() -> Self {
        Self::from_env_or_exit_()
    }

    #[allow(dead_code)]
    pub fn from_env() -> xflags::Result<Self> {
        Self::from_env_()
    }

    #[allow(dead_code)]
    pub fn from_vec(args: Vec<std::ffi::OsString>) -> xflags::Result<Self> {
        Self::from_vec_(args)
    }
}
// generated end

pub trait Cmd {
    fn run(self) -> anyhow::Result<()>;
}
