[package]
name = "fading-ls"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
crop.workspace = true
env_logger.workspace = true
log.workspace = true
papaya.workspace = true
serde.workspace = true
tokio.workspace = true
toml.workspace = true
tower-lsp-server.workspace = true
tree-sitter.workspace = true
tree-sitter-md.workspace = true

[dev-dependencies]
criterion.workspace = true
proptest.workspace = true
tokio.workspace = true

[[bench]]
name = "diagnostics"
harness = false
