use-grammars = { only = ["markdown"] }

[language-server.fading]
command = "fading"
args = ["ls"]

[[language]]
name = "markdown"
file-types = [{ glob = "entries/*.md" }]
language-servers = ["fading"]
code-actions-on-save = ["source.updateMetadata.fading"]

[language.soft-wrap]
enable = true
max-wrap = 3
max-indent-retain = 0
wrap-indicator = ""
wrap-at-text-width = false

[language.auto-pairs]
# halfwidth
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"
'`' = '`'
# fullwidth
'（' = '）'
'『' = '』'
'「' = '」'
'“' = '”'
'‘' = '’'
