xflags::xflags! {
    src "./src/flags.rs"

    /// Manage tree-sitter parser
    cmd xtask {

        /// Compress generated parser.c with zstd
        cmd compress {}

        /// Generate parser.c from grammar.js using tree-sitter CLI
        cmd generate {}

        /// Vendor grammar files from `tree-sitter-grammars/tree-sitter-markdown`
        cmd vendor {}
    }
}

// generated start
// The following code is generated by `xflags` macro.
// Run `env UPDATE_XFLAGS=1 cargo build` to regenerate.
#[derive(Debug)]
pub struct Xtask {
    pub subcommand: XtaskCmd,
}

#[derive(Debug)]
pub enum XtaskCmd {
    Compress(Compress),
    Generate(Generate),
    Vendor(Vendor),
}

#[derive(Debug)]
pub struct Compress;

#[derive(Debug)]
pub struct Generate;

#[derive(Debug)]
pub struct Vendor;

impl Xtask {
    #[allow(dead_code)]
    pub fn from_env_or_exit() -> Self {
        Self::from_env_or_exit_()
    }

    #[allow(dead_code)]
    pub fn from_env() -> xflags::Result<Self> {
        Self::from_env_()
    }

    #[allow(dead_code)]
    pub fn from_vec(args: Vec<std::ffi::OsString>) -> xflags::Result<Self> {
        Self::from_vec_(args)
    }
}
// generated end
