xflags::xflags! {
    src "./src/flags.rs"

    /// CLI for the `fading` entries
    cmd task {

        /// Generate a monthly entry
        cmd generate {}

        /// Compile entries to HTML
        cmd compile {}
    }
}

// generated start
// The following code is generated by `xflags` macro.
// Run `env UPDATE_XFLAGS=1 cargo build` to regenerate.
#[derive(Debug)]
pub struct Task {
    pub subcommand: TaskCmd,
}

#[derive(Debug)]
pub enum TaskCmd {
    Generate(Generate),
    Compile(Compile),
}

#[derive(Debug)]
pub struct Generate;

#[derive(Debug)]
pub struct Compile;

impl Task {
    #[allow(dead_code)]
    pub fn from_env_or_exit() -> Self {
        Self::from_env_or_exit_()
    }

    #[allow(dead_code)]
    pub fn from_env() -> xflags::Result<Self> {
        Self::from_env_()
    }

    #[allow(dead_code)]
    pub fn from_vec(args: Vec<std::ffi::OsString>) -> xflags::Result<Self> {
        Self::from_vec_(args)
    }
}
// generated end

pub trait Cmd {
    fn run(self) -> anyhow::Result<()>;
}
